CREATE TABLE IF NOT EXISTS "user_role" (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    FOREIGN KEY(USER_ID) REFERENCES "user"(ID),
    FOREIGN KEY(ROLE_ID) REFERENCES "role"(ID)
    );
